### ISSUE TITLE
Use cljdoc for documentation?

### ISSUE THREAD

**Issue by martinklepsch** [nnichols/nature#8]
Hey Nick! 

This library looks really nice, you seem to have paid a lot of attention to the documentation. 👍 

I just wanted to make you aware that documentation has also been built on cljdoc: https://cljdoc.org/d/nature/nature/0.1.1

(I noticed this because cljdoc builds documentation automatically and the name stood out, so I went to check it out 🙂)

This might be more convenient than remembering to update Codox documentation on every release. You can also integrate more articles (saw some [here](https://nnichols.github.io/code/nature/reproduction)).

There's some [additional documentation for library authors](https://github.com/cljdoc/cljdoc/blob/master/doc/userguide/for-library-authors.adoc) on how to get the most out of cljdoc.

Cheers!

**Comment by nnichols** [comment]
Thanks for letting me know!

I really like what you've made, so I transitioned what used to be docs/api to refer to cljdoc instead.

Thanks!

**Comment by martinklepsch** [comment]
Well, that's awesome! 

In case you're looking for more documentation on integrating more Markdown/Asciidoc files see the [documentation on articles](https://github.com/cljdoc/cljdoc/blob/master/doc/userguide/for-library-authors.adoc#articles).

Cheers
